# Book settings
title:
author: World Bank Development Data Group
logo: docs/images/logo.png

repository:
    url: https://github.com/datapartnership/vulnerability-to-heatwaves-in-india
    branch: main

html:
    home_page_in_navbar: true
    use_edit_page_button: true
    use_repository_button: true
    use_issues_button: true
    baseurl: https://github.com/datapartnership/template

#######################################################################################
# Execution settings
execute:
    execute_notebooks: force
    allow_errors: true
    exclude_patterns:
        - notebooks/*.ipynb

only_build_toc_files: true
